spring:
  application:
    name: auth-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: false

  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE:true}

  security:
    oauth2:
      client:

        registration:

          google:
            client-name: Google
            provider: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"

          microsoft:
            client-name: Microsoft
            provider: microsoft
            client-id: ${MICROSOFT_CLIENT_ID}
            client-secret: ${MICROSOFT_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"


        provider:

          google:
            issuer-uri: https://accounts.google.com

          microsoft:
            issuer-uri: https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0


server:
  port: ${SERVER_PORT:8080}
  forward-headers-strategy: framework


logging:
  level:
    root: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: DEBUG


app:
  login-page: ${LOGIN_PAGE:/login}

  oauth:
    issuer: ${AUTH_ISSUER:http://localhost}
    client-id: ${APP_OAUTH_CLIENT_ID:public-client}
    client-secret: ${APP_OAUTH_CLIENT_SECRET:change-me}
    redirect-uri: ${APP_OAUTH_REDIRECT_URI:http://localhost/oauth/callback}